### ISSUE TITLE
Intermediate verification not working

### ISSUE THREAD

**Issue by cadir** [hsk81/amazon-alexa-python#1]
Thanks for this code and the post.   Very helpful.  However, it looks like the intermediate certificate chain validation doesn't work as written.  Specifically, as each intermediate certificate is verified in verify_pem, it needs to be added to the ca_store so that certificates further down the chain can be validated.

**Comment by notexeditor** [comment]
@cadir Please provide a corresponding pull-request. Amazon's Alexa team had done such a terribly bad job, it took us literally almost two months to come up with the correct `SignatureHook`. I had done this for a customer project, and we've put it out there so other poor souls don't need to suffer the same waste-of-time, we had to go through. Short, I've zero inclinations to spent any micro-second further on this authentication non-sense, but I'm very much open to integrate corresponding pull-requests. ;-)
