### ISSUE TITLE
I have a question 

### ISSUE THREAD

**Issue by stnc** [hsk81/amazon-alexa-python#2]
tr: 
abi herseyi anladim da bu http request deki signature nasil olusturacagim bunu anlamadim 
https://developer.amazon.com/en-US/docs/alexa/custom-skills/host-a-custom-skill-as-a-web-service.html#checking-the-signature-of-the-request
burada anlatiyor ama cozemedim bunu ben 
bana yardimci olur musun?

**Comment by notexeditor** [comment]
Selam Selman,

Beş sene öncesinden yaptığım bir proje, ve detaylarını hiç hatırlamıyorum.
Ama bir blog yazmışım fii tarihinde, belki işinize yarar:

   -
   https://github.com/hsk81/amazon-alexa-python/blob/master/calaganne.blogspot.com/2018-03-29T14_00_56.789Z.md

--
Hasan Karahan|CEO
Blackhan Software Ltd
